#
# Network configuration
#

# Wireless access point
wap_ip_octet_1: 10
wap_ip_octet_2: 13
wap_ip_octet_3: 37
wap_ip_octet_4: 1
wap_device: wlan0

internal_ip_octet_1: "{{ wap_ip_octet_1 }}"
internal_ip_octet_2: "{{ wap_ip_octet_2 }}"
internal_ip_octet_3: "{{ wap_ip_octet_3 }}"
internal_ip_octet_4: "{{ wap_ip_octet_4 }}"

dns_network_device: "{{ router_internal_nic }}"

external_wireless_nic: wlan1
router_access_point_nic: wlan0
router_external_nic: eth0
router_internal_nic: "{{ wap_device }}"

# IP address of the DNS server
dns_ip_octet_1: "{{ wap_ip_octet_1 }}"
dns_ip_octet_2: "{{ wap_ip_octet_2 }}"
dns_ip_octet_3: "{{ wap_ip_octet_3 }}"
dns_ip_octet_4: "{{ wap_ip_octet_4 }}"

dns_domain: local
dns_host: catpoo


internal_hosts:
  - name: catpoo
    mac: "66:66:66:66:66:66"
    ip: 1
  - name: router
    mac: "66:66:66:66:66:66"
    ip: 1
