---

- name: Install PHP
  apt: name="{{ item }}" state=present
  with_items:
    - php5
    - php5-cgi
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-json
    - php5-mysqlnd
    - php5-sqlite
    - php-apc

- name: Install Apache
  apt: name="{{ item }}" state=present
  with_items:
    - apache2
    - libapache2-mod-php5

