---

- name: Install PHP
  sudo: yes
  apt: name="{{ item }}" state=present
  with_items:
    - php5
    - php5-cgi
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-json
    - php5-mysqlnd
    - php5-sqlite
    - php-apc

- name: Install Apache
  sudo: yes
  apt: name="{{ item }}" state=present
  with_items:
    - apache2
    - libapache2-mod-php5

- name: Configure Apache modules
  sudo: yes
  apache2_module: state=present name="{{ item }}"
  with_items:
    - ssl
    - rewrite

- name: Update Apache PHP settings
  sudo: yes
  lineinfile:
    dest="/etc/php5/apache2/php.ini"
    line="{{ item }}"
  with_items:
    - "max_execution_time = {{ apache_php_max_execution_time }}"
    - "post_max_size = {{ apache_php_post_max_size }}"
    - "upload_max_size = {{ apache_php_upload_max_size }}"
    - "upload_max_filesize = {{ apache_php_upload_max_filesize }}"
    - "memory_limit = {{ apache_php_memory_limit }}"

- name: Restart Apache
  sudo: yes
  service: name=apache2 state="{{ item }}"
  with_items:
    - stopped
    - started

- name: Disable default Apache site
  sudo: yes
  shell: a2dissite 000-default
