---

- hosts: all
  become: true
  become_user: root
  # Disable gathering of facts until we're sure that python is installed
  gather_facts: False
  pre_tasks:
    - name: Install Python for Ansible's use
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""

    - setup: # Now do the `gather_facts` step

# Python should be installed at this point. Carry on usual.

- hosts: all
  roles:
    - common

- hosts: dev-machines
  roles:
    - dev-machine

- hosts: photoservers
  roles:
    - "photo-server"

- hosts: webservers
  roles:
    - "web-server"

- hosts: timemachines
  roles:
    - "time-machine"

- hosts: sqlservers
  roles:
    - "sql-server"

- hosts: catpoos
  roles:
    - catpoo

- hosts: pucks
  roles:
   - puck

- hosts: plexservers
  roles:
    - "plex-server"

- hosts: minecraft
  roles:
    - minecraft

- hosts: desktops
  roles:
    - desktop

- hosts: 3d
  roles:
    - 3d

- hosts: motionservers
  roles:
    - "motion-server"

- hosts: syncservers
  roles:
    - "sync-server"
