---

- hosts: all
  sudo: yes
  roles:
    - common

- hosts: photoservers
  sudo: yes
  roles:
    - "web-server"
    - "sql-server"
    - "samba-server"
    - "photo-server"

- hosts: webservers
  sudo: yes
  roles:
    - "web-server"
    - "sql-server"

- hosts: timemachines
  sudo: yes
  roles:
    - "time-machine"

- hosts: sqlservers
  sudo: yes
  roles:
    - "sql-server"

- hosts: catpoos
  sudo: yes
  roles:
    - "web-server"
    - "catpoo"
