---

- hosts: all
  roles:
    - common

- hosts: devmachines
  roles:
    - dev-machine

- hosts: photoservers
  roles:
    - "photo-server"

- hosts: webservers
  roles:
    - "web-server"

- hosts: timemachines
  roles:
    - "time-machine"

- hosts: sqlservers
  roles:
    - "sql-server"

- hosts: plexservers
  roles:
    - "plex-server"

- hosts: minecraft
  roles:
    - minecraft

- hosts: desktops
  roles:
    - desktop

- hosts: 3d
  roles:
    - 3d

- hosts: motionservers
  roles:
    - "motion-server"

- hosts: hypervisors
  roles:
    - hypervisor

- hosts: clouds
  roles:
    - cloud
