---

- hosts: all
  sudo: yes
  roles:
    - common

- hosts: photoservers
  sudo: yes
  roles:
    - webserver
    - sqlserver
    - photoserver

- hosts: webservers
  sudo: yes
  roles:
    - webserver
    - sqlserver

- hosts: sqlservers
  sudo: yes
  roles:
    - sqlserver
