---

- hosts: all
  sudo: yes
  roles:
    - common

- hosts: photoservers
  sudo: yes
  roles:
    - webserver
    - sqlserver
    - photoserver
    - samba

- hosts: webservers
  sudo: yes
  roles:
    - webserver
    - sqlserver

- hosts: timemachines
  sudo: yes
  roles:
    - timemachine

- hosts: sqlservers
  sudo: yes
  roles:
    - sqlserver

