---

- hosts: all
  roles:
    - "common"

- hosts: photoservers
  roles:
    - "web-server"
    - "sql-server"
    - "samba-server"
    - "photo-server"

- hosts: webservers
  roles:
    - "web-server"
    - "sql-server"

- hosts: timemachines
  roles:
    - "time-machine"

- hosts: sqlservers
  roles:
    - "sql-server"

- hosts: catpoos
  roles:
    - "dns-server"
    - "web-server"
    - "catpoo"

