---

- hosts: all
  roles:
    - "common"

- hosts: photoservers
  roles:
    - "photo-server"

- hosts: webservers
  roles:
    - "web-server"

- hosts: timemachines
  roles:
    - "time-machine"

- hosts: sqlservers
  roles:
    - "sql-server"

- hosts: catpoos
  roles:
    - "catpoo"

- hosts: pucks
  roles:
   - "router"
