---

- hosts: all
  sudo: yes
  roles:
      - common
- hosts: zanzou
  sudo: yes
  roles:
    - common
  # vars_files:
  #     - "../ansible/machines/{{ HOSTNAME }}.yml"
  # tasks:
  #     - include: tasks/configure-system.yml
  #     - include: tasks/configure-users.yml
  #     - include: tasks/configure-networking.yml
  #     - include: tasks/configure-misc.yml
