---

- hosts: all
  sudo: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-minimal aptitude

- hosts: all
  roles:
    - common

- hosts: dev-machines
  roles:
    - dev-machine

- hosts: photoservers
  roles:
    - "photo-server"

- hosts: webservers
  roles:
    - "web-server"

- hosts: timemachines
  roles:
    - "time-machine"

- hosts: sqlservers
  roles:
    - "sql-server"

- hosts: catpoos
  roles:
    - catpoo

- hosts: pucks
  roles:
   - puck

- hosts: plexservers
  roles:
    - "plex-server"

- hosts: minecraft
  roles:
    - minecraft
