#
# Programming languages
#
- name: Install build utilities
  apt: name="{{ item }}"
  with_items:
  - autoconf
  - automake
  - byacc
  - build-essential
  - flex
  - libtool
  - m4
  - make

- name: Install GCC, G++
  apt: name="{{ item }}"
  with_items:
  - gpp
  - gcc
  - g++

- name: Install Python
  apt: name="{{ item }}"
  with_items:
  - python
  - python-pysqlite2

#
# Node and utilites
#
#- name: Download latest Node
#  command: wget http://node-arm.herokuapp.com/node_latest_armhf.deb
#  when: skip_update == false
#
#- name: Install Node
#  command: dpkg -i node_latest_armhf.deb
#  when: skip_update == false
#
#- name: Node cleanup
#  command: rm node_latest_armhf.deb
#  when: skip_update == false

- name: Install Node and NPM
  apt: name="{{ item }}"
  with_items:
  - nodejs
  - npm

- name: Install Grunt CLI
  command: npm install -g grunt-cli

