---

- name: "Set HDMI Resolution"
  template:
    src: boot/config.txt.j2
    dest: /boot/config.txt

- name: "Set PS1"
  lineinfile:
    dest: "/root/.bashrc"
    line: 'PS1="${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[01;37m\]:\[\033[00;31m\]\w\\[\033[01;37m\]#\[\033[00m\] "'
    regexp: '^PS1'
    state: present

- name: "Alias"
  lineinfile:
    dest: "/root/.bashrc"
    line: "alias ls='ls --color=auto'"
    regexp: "^alias ls"
    state: present

#- name: "Set the user shell prompt"
#  lineinfile:
#    dest: "{{ ansible_env.HOME }}/.bashrc"
#    line: 'PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u\[\033[01;37m\]@\[\033[01;36m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;37m\]\$\[\033[00m\] "'
#    state: present

- name: "Configure LightDM"
  template:
    src: etc/lightdm/lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf

- name: "Set default runlevel"
  lineinfile:
    dest: "/etc/inittab"
    state: present
    regexp: "id:.:initdefault:"
    line: "id:3:initdefault:"

- name: "Install XInput"
  apt: name=xinput

- name: "Install XInput calibration software"
  git:
    accept_hostkey: yes
    clone: yes
    dest: "/usr/local/src/xinput_calibrator/"
    recursive: yes
    repo: "https://github.com/tias/xinput_calibrator.git"
    version: v0.7.5

- name: "Compile XInput calibrator"
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/xinput_calibrator
  with_items:
    - "[ -e Makefile ] || ./autogen.sh"
    - "make -j 2"
    - "make install"

- name: "Make sure xorg configuration directory exists"
  file:
    path: /etc/X11/xorg.conf.d/
    state: directory

- name: "Update touchscreen calibration"
  template:
    dest: /etc/X11/xorg.conf.d/99-calibration.conf
    src: etc/X11/xorg.conf.d/99-calibration.conf.j2

