---

- name: "Set HDMI Resolution"
  template:
    src: boot/config.txt.j2
    dest: /boot/config.txt

- name: "Set PS1"
  lineinfile:
    dest: "/root/.bashrc"
    line: 'PS1="${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[01;37m\]:\[\033[00;31m\]\w\\[\033[01;37m\]#\[\033[00m\] "'
    regexp: '^PS1'
    state: present

- name: "Bash Aliases for root"
  blockinfile:
    dest: "/root/.bashrc"
    state: present
    content: |
      # enable color support of ls and also add handy aliases
      if [ -x /usr/bin/dircolors ]; then
          test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
          alias ls='ls --color=auto'
          #alias dir='dir --color=auto'
          #alias vdir='vdir --color=auto'

          alias grep='grep --color=auto'
          alias fgrep='fgrep --color=auto'
          alias egrep='egrep --color=auto'
      fi

- name: "Configure LightDM"
  template:
    src: etc/lightdm/lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf

- name: "Set default runlevel"
  lineinfile:
    dest: "/etc/inittab"
    state: present
    regexp: "id:.:initdefault:"
    line: "id:3:initdefault:"

- name: "Make sure LightDM is enabled in default runlevel"
  service:
    enabled: yes
    runlevel: 3
    name: lightdm

- name: "Install XInput"
  apt: name=xinput

- name: "Compile XInput calibrator"
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/xinput_calibrator
  with_items:
    - "[ -e Makefile ] || ./autogen.sh"
    - "make -j 2"
    - "make install"

- name: "Make sure xorg configuration directory exists"
  file:
    path: /etc/X11/xorg.conf.d/
    state: directory

- name: "Update touchscreen calibration"
  template:
    dest: /etc/X11/xorg.conf.d/99-calibration.conf
    src: etc/X11/xorg.conf.d/99-calibration.conf.j2

