---
#
# Tasks meant to be run as a regular user
#
- name: "Install XInput calibration software"
  git:
    accept_hostkey: yes
    clone: yes
    dest: "{{ ansible_env.HOME }}/src/xinput_calibrator/"
    recursive: yes
    repo: "https://github.com/tias/xinput_calibrator.git"
    version: v0.7.5

- name: "Compile XInput calibrator"
  shell: "{{ item }}"
  args:
    chdir: "{{ ansible_env.HOME }}/src/xinput_calibrator/"
  with_items:
    - "[ -e Makefile ] || ./autogen.sh"
    - "make -j 2"

- name: "Install XInput calibrator"
  sudo: yes
  shell: make install
  args:
    chdir: "{{ ansible_env.HOME }}/src/xinput_calibrator/"

- name: "Configure LightDM"
  sudo: yes
  template:
    src: etc/lightdm/lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf

