---
#
# Configures and installs MariaDB
#
- name: Add MariaDB certificates
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xcbcb082a1bb943db"
    state: present
  when: skip_update == false

- name: Add MariaDB repository
  apt_repository:
    repo: 'deb http://ftp.utexas.edu/mariadb/repo/10.1/ubuntu trusty main'
    state: present
  when: skip_update == false

- name: Update APT
  apt: update_cache=yes
  when: skip_update == false

- name: Install MariaDB
  apt: name="{{ item }}" state=present
  with_items:
    - mariadb-server
    - mariadb-client
