---
#
# Configures and installs MariaDB
#
- name: Add MariaDB certificates
  apt_key:
    server: hkp://keyserver.ubuntu.com:80
    id: 0xcbcb082a1bb943db
    state: present

- name: Add MariaDB repository
  apt_repository:
    repo: 'deb http://ftp.utexas.edu/mariadb/repo/10.1/ubuntu trusty main'
    state: present

- name: Update APT
  apt: update_cache=yes

- name: Install MariaDB
  apt: name="{{ item }}" state=present
  with_items:
    - mariadb-server
    - mariadb-client
