---
#
# Main configuration file for setting up a photo
# server running Lychee
#

- name: Install lychee Apache configuration
  template:
    src: "etc/apache2/sites-available/lychee.conf.j2"
    dest: "/etc/apache2/sites-available/lychee.conf"

- name: Disable default Apache site
  command: a2dissite 000-default

- name: Enable Lychee Apache site
  command: a2ensite lychee

- name: Create Lychee user account
  user:
    name: "{{ lychee_user }}"
    shell: "/bin/bash"
    state: present
    ssh_key_type: rsa
    createhome: yes
    home: "{{ lychee_home }}"

- name: Clone Lychee repository
  become: yes
  become_user: "{{ lychee_user }}"
  become_method: sudo
  git:
    clone: yes
    repo: "{{ lychee_repository }}"
    dest: "{{ lychee_document_root }}"
    version: "{{ lychee_version }}"

- name: "Setup Apache/Lychee permissions"
  acl:
    name: "{{ lychee_document_root }}/{{ item }}"
    entity: www-data
    permissions: rwx
    recursive: yes
    state: present
    etype: user
  with_items:
    - data
    - uploads

- name: Configure Lychee
  template:
    src: "home/lychee/lychee/data/config.php.j2"
    dest: "{{ lychee_document_root }}/data/config.php"

- name: Restart Apache
  service: name=apache2 state="{{ item }}"
  with_items:
    - stopped
    - started

- name: Setup Lychee Database
  command: "echo '{{ item }}' | mysql -u root"
  with_items:
    - "CREATE DATABASE IF NOT EXISTS lychee"
    - "CREATE USER IF NOT EXISTS lychee@localhost"
    - "GRANT ALL ON {{ lychee_db_database }}.* TO {{ lychee_db_user }}@localhost"

- name: Lock Lychee user account
  user: name="{{ lychee_user }}" shell="/bin/false"
