---

- name: Configure SAMBA
  blockinfile:
    dest: "/etc/samba/smb.conf"
    state: present
    block: |
      [Lychee Dropbox]
      comment = Lychee bulk import dropbox
      create mask = 0777
      force user = nobody
      guest account = nobody
      guest ok = yes
      guest only = yes
      path = {{ lychee_document_root }}/uploads/import/
      read only = no

- name: "Setup Samba/Lychee DropBox permissions (Step #1)"
  acl:
    default: yes
    entity: nobody
    etype: user
    name: "{{ lychee_document_root }}/uploads/import"
    permissions: rwx
    recursive: yes
    state: present

- name: "Setup Samba/Lychee DropBox permissions (Step #2)"
  acl:
    default: yes
    entity: "{{ lychee_user }}"
    etype: user
    name: "{{ lychee_document_root }}/uploads/import"
    permissions: rwx
    recursive: yes
    state: present

- name: "Setup Samba/Lychee DropBox permissions (Step #3)"
  acl:
    default: yes
    entity: "www-data"
    etype: user
    name: "{{ lychee_document_root }}/uploads/import"
    permissions: rwx
    recursive: yes
    state: present

- name: "Setup Samba/Lychee DropBox permissions (Step #4)"
  file:
    path: "{{ lychee_document_root }}/uploads/import/index.html"
    owner: root
    group: root


- name: "Setup Samba/Lychee DropBox permissions (Step #5)"
  shell: "setfacl -x 'u:{{ lychee_user }}' {{ lychee_document_root }}/uploads/import/index.html"
