---
#
# Packages to be installed in this section are based on instructions
# from http://ubuntuforums.org/showthread.php?t=2105755
#
- name: Install Time Machine support packages
  sudo: yes
  apt: name="{{ item }}"
  with_items:
    - netatalk
    - libc6-dev
    - avahi-daemon
    - libnss-mdns

#
# Configure network drives
#
- name: Create Time Machine mount point
  sudo: yes
  file: path="{{ time_machine_mount_point }}" state=directory mode=0777

- name: Mount Time Machine at boot
  sudo: yes
  mount:
    fstype: ext4
    name: "{{ time_machine_mount_point }}"
    opts: "defaults,auto,nofail"
    src: "{{ time_machine_drive }}"
    state: present
  when: time_machine_drive is defined
  notify: Mount Time Machine partition

- name: Clear Time Machine mount
  sudo: yes
  mount:
    name: "{{ time_machine_mount_point }}"
    state: absent
  when: time_machine_drive is undefined
  notify: Unmount Time Machine partition
