---
#
# Packages to be installed in this section are based on instructions
# from http://ubuntuforums.org/showthread.php?t=2105755
#
- name: Install Time Machine support packages
  sudo: yes
  apt: name="{{ item }}"
  with_items:
    - netatalk
    - libc6-dev
    - avahi-daemon
    - libnss-mdns

#
# Configure network drives
#
- name: Create Time Machine mount point
  sudo: yes
  file: path="{{ time_machine_mount_point }}" state=directory mode=0777

- name: Mount Time Machine at boot
  sudo: yes
  lineinfile: dest="/etc/fstab" line="{{ time_machine_drive }} {{ time_machine_mount_point }} ext4  defaults,auto,nofail 0 0"
  when: time_machine_drive != ""

- name: Make sure new drives are mounted
  sudo: yes
  shell: mount -a
