---

- name: Disable screen startup message
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.screenrc"
    line: "startup_message off"
    create: yes
    state: present

- name: Vim configuration settings
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.vimrc"
    create: yes
    content: |
      set tabstop=2
      syntax on
      colorscheme elflord
