---
- name: Install DHCPD
  sudo: yes
  apt: name=isc-dhcp-server

- name: Install Bridge Utils
  apt: name=bridge-utils

- name: Install ddclient
  apt: name=ddclient

- name: Install SSHFS
  apt: name=sshfs

- name: Install UPnP daemon
  apt: name="{{ item }}" state=latest
  with_items:
    - miniupnpc
    - miniupnpd

- name: Configure UPnP daemon
  template:
    src: etc/default/miniupnpd.j2
    dest: /etc/default/miniupnpd