---

- name: Install SAMBA
  sudo: yes
  apt: name="{{ item }}"
  with_items:
    - samba
    - smbclient

- name: Install base SAMBA configuration
  sudo: yes
  template:
    src: "etc/samba/smb.conf.j2"
    dest: "/etc/samba/smb.conf"

- name: Stop SAMBA
  sudo: yes
  service: name="{{ item }}" state=stopped
  with_items:
  - nmbd
  - smbd

- name: Start SAMBA
  sudo: yes
  service: name="{{ item }}" state=started
  with_items:
  - nmbd
  - smbd
